version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_demo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'haopn'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
      # Where our data will be persisted
    volumes:
      - my-sql-db:/var/lib/mysql
# Names our volume
volumes:
  my-sql-db:

# connect: mysql -u haopn -p'1234' -h 127.0.0.1 -P 3307